name: Svelte blog CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types:
      - webhook

env:
  VITE_SPACE_UID: ${{ secrets.VITE_SPACE_UID }}
  VITE_CDN_API_TOKEN: ${{ secrets.VITE_CDN_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm install

    - name: install playwright
      run: npx playwright install
      if: github.event_name != 'repository_dispatch'
    - name: run test
      run: npm test
      if: github.event_name != 'repository_dispatch'

    - run: npm run build

    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
